language: python
python:
  - "2.6"
  - "2.7"
# command to install dependencies
install: "pip install -r requirements.txt"

services:
  - redis-server
  
before_script:
  - psql -c 'create database travis_ci_test;' -U postgres